package io.catalyze.sdk.android.umls;

/**
 * Created by mvolkhart on 8/26/13.
 */
public enum UMLS {

    AIR, ALT, AOD, AOT, BI, CCC, CCPSS, CCS, CHV, COSTAR, CPM, CPTSP, CPT, CSP, CST, DDB,
    DMDICD10, DMDUMD, DSM3R, DSM4, DXP, FMA, GO, GS, HCDT, HCPCS, HCPT, HGNC, HL7V2_5("HL7V2.5"),
    HL7V3_0("HL7V3.0"), HLREL, ICD10AE, ICD10AMAE, ICD10AM, ICD10CM, ICD10DUT, ICD10PCS, ICD10,
    ICD9CM, ICF_CY("ICF-CY"), ICF, ICNP, ICPC2EDUT, ICPC2EENG, ICPC2ICD10DUT,
    ICPC2ICD10ENG, ICPC2P, ICPC, ICPCBAQ, ICPCDAN, ICPCDUT, ICPCFIN, ICPCFRE, ICPCGER, ICPCHEB,
    ICPCHUN, ICPCITA, ICPCNOR, ICPCPOR, ICPCSPA, ICPCSWE, JABL, KCD5, LCH, LNC, LNC_AD8,
    LNC_ASQ_3, LNC_BRADEN, LNC_CAM, LNC_FACIT, LNC_FLACC, LNC_MDS20, LNC_MDS30, LNC_MLHFQ,
    LNC_NEUROQOL, LNC_NPUAP, LNC_OASIS, LNC_OPTIMAL, LNC_PHQ_9, LNC_RHO, LNC_SPERTUS, LNC_VR_12,
    LNC_WHO, MBD, MCM, MDDB, MDR, MDRCZE, MDRDUT, MDRFRE, MDRGER, MDRHUN, MDRITA, MDRJPN, MDRPOR,
    MDRSPA, MED, MEDCIN, MEDLINEPLUS, MMSL, MMX, MSH, MSHCZE, MSHDUT, MSHFIN, MSHFRE,
    MSHGER, MSHITA, MSHJPN, MSHLAV, MSHNOR, MSHPOL, MSHPOR, MSHRUS, MSHSCR, MSHSPA, MSHSWE, MTH,
    MTHCH, MTHFDA, MTHHH, MTHHL7V2_5("MTHHL7V2.5"), MTHICD9, MTHICPC2EAE, MTHICPC2ICD107B,
    MTHICPC2ICD10AE, MTHMST, MTHMSTFRE, MTHMSTITA, MTHSPL, NAN, NCBI, NCI, NCISEER, NDDF, NDFRT,
    NEU, NIC, NLM_MED("NLM-MED"), NOC, OMIM, OMS, PCDS, PDQ, PNDS, PPAC, PSY, QMR, RAM, RCD,
    RCDAE, RCDSA, RCDSY, RXNORM, SCTSPA, SCTUSX, SNM, SNMI, SNOMEDCT, SOP,
    SPN, SRC, TKMT, ULT, UMD, USPMG, UWDA, VANDF, WHO, WHOFRE, WHOGER, WHOPOR, WHOSPA;


    private final String mJson;

    private UMLS(String json) {
        mJson = json;
    }

    private UMLS() {
        mJson = this.name();
    }

    @Override
    public String toString() {
        return mJson;
    }
}
